version: "3.8"

services:
  frontend:
    build: .
    container_name: my-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Mac/Windows에서 파일 변경 감지용
    command: npm run dev
